# Generated by Django 2.2.2 on 2021-02-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('genre', models.CharField(max_length=10, verbose_name='genre')),
                ('year', models.CharField(max_length=5, verbose_name='year')),
                ('date', models.CharField(max_length=10, verbose_name='date')),
                ('rating', models.CharField(max_length=10, verbose_name='rating')),
                ('vote_count', models.CharField(max_length=10, verbose_name='vote_count')),
                ('plot', models.TextField(verbose_name='plot')),
                ('main_act', models.CharField(max_length=20, verbose_name='main_act')),
                ('supp_act', models.CharField(max_length=20, verbose_name='supp_act')),
                ('page_url', models.URLField(verbose_name='page_url')),
                ('img_url', models.URLField(verbose_name='img_url')),
            ],
        ),
    ]
