# Generated by Django 2.2.2 on 2021-02-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_movieinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.TextField(max_length=2, verbose_name='rating')),
            ],
        ),
    ]
